# https://taskfile.dev

version: '3'

vars:
  GREETING: Taskfile for Expense Tracker API
  DRIZZLE_CONFIG_PATH: ./src/config
  DB_SEED_PATH: ./src/db/seeders

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  drizzle_push:
    cmds:
      - echo "Pushing drizzle schema"
      - pnpm exec drizzle-kit push --config={{.DRIZZLE_CONFIG_PATH}}/drizzle.config.local.ts
    silent: true

  drizzle_generate:
    cmds:
      - echo "Generating drizzle schema"
      - pnpm exec drizzle-kit generate --config={{.DRIZZLE_CONFIG_PATH}}/drizzle.config.local.ts
    silent: true

  db_migrate_up:
    deps:
      - drizzle_generate
    cmds:
      - echo "Migrating drizzle schema"
      - pnpm exec drizzle-kit migrate --config={{.DRIZZLE_CONFIG_PATH}}/drizzle.config.local.ts
    silent: false

  db_migrate_down:
    cmds:
      - echo "Migrating down drizzle schema"
      - pnpm exec tsx {{.DB_SEED_PATH}}/resetdb.ts
    silent: true

  db_seed:
    cmds:
      - echo "Executing database seeders\n------------------\n"
      - pnpm exec tsx {{.DB_SEED_PATH}}/index.ts
    silent: true

  dev:
    cmds:
      - echo "Starting development server"
      - pnpm dev
    silent: true

  postgres_up:
    cmds:
      - echo "Starting postgres"
      - docker compose up postgres -d
    silent: true

  postgres_down:
    cmds:
      - echo "Stopping postgres"
      - docker compose down postgres
    silent: true

  redis_up:
    cmds:
      - echo "Starting redis"
      - docker compose up redis -d
    silent: true

  redis_down:
    cmds:
      - echo "Stopping redis"
      - docker compose down redis
    silent: true
